#!/bin/bash

/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -s

echo " "
echo " Current Connection -------------------------------------------------------------------"
echo " "

/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I
